flaskBlog/posts/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    picture = FileField('Post Profile Picture', validators=[FileAllowed(['jpg', 'png', 'jpeg', 'webp'])])
    submit = SubmitField('Post')


""" Descriptions """

# For flask_wtf: pip install flask flask-wtf

"""
After Installing New Packages Every Time You Need To: 
Update requirements.txt: pip freeze > requirements.txt
"""

flaskBlog/main/routes.py
from flask import Blueprint, request, render_template
from flaskBlog.models import Post

main = Blueprint('main', __name__)


# Those two routes "/" and "/home" are being handled by same home function:
@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template("home.html", posts=posts)


@main.route("/about")
def about():
    return render_template("about.html", title='About')


""" Descriptions """

# render_template is for html files, paginate is for pagination

# Blueprint:
"""
Flask mein Blueprint ek module hai jo apki application ko chote-chote parts mein divide 
karne ki facility deta hai.
"""

# request.args.get:
"""
'request.args' URL parameters ko represent karta hai.
.get('page') yai function URL mein 'page' parameter ko get karta hai.
"""

# page = request.args.get('page', 1, type=int)
"""
request.args.get('page', 1, type=int) ka matlab hai ke URL mein agar page parameter diya gaya hai, to uski value le lo. Agar page parameter nahi diya gaya, to default value 1 set kar lo,
type=int means page value should be integer
"""

# posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
"""
Post.date_posted.desc(): new post will be shown on top
per_page=1 means eik page pr eik post hogi
"""

# `f` string ka istemal hota hai username ke data ko message ke saath include karne ke liye.

flaskBlog/posts/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, request, abort
from flaskBlog import db
from flaskBlog.models import Post
from flask_login import current_user, login_required

from flaskBlog.posts.forms import PostForm
from flaskBlog.common.common import save_picture

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    picture_file = 'default.jpg'
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data, "post_profile_pics")
        post = Post(title=form.title.data, content=form.content.data, image_file=picture_file, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your Post Has Been Created!', 'success')
        return redirect(url_for('main.home'))
    image_file = url_for('static', filename='post_profile_pics/' + picture_file)
    return render_template("create_post.html", title='New Post', image_file=image_file, form=form, legend='New Post')


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    current_post_image = post.image_file
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data, "post_profile_pics")
            current_post_image = picture_file
        post.title = form.title.data
        post.content = form.content.data
        post.image_file = current_post_image
        db.session.commit()
        flash('Your Post Has Been Updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    image_file = url_for('static', filename='post_profile_pics/' + current_post_image)
    return render_template("create_post.html", title='Update Post', image_file=image_file, form=form,
                           legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your Post Has Been Deleted!', 'success')
    return redirect(url_for('main.home'))


""" Descriptions """

# render_template is for html files, url_for is for css files, flash is for alert messages

# request:
"""
Gives you access to details of the incoming HTTP request, such as form data, 
query parameters, and headers.
"""

# abort(403)
"""
abort is a function that allows you to generate a specific HTTP error code (like 404 or 403) 
to stop the request and return an error response.

if post.author != current_user:
Check if post author not equal to current login user then not access the update route
"""

# db are instance that we define in __init__.py

# Blueprint:
"""
Flask mein Blueprint ek module hai jo apki application ko chote-chote parts mein divide 
karne ki facility deta hai.
"""

# current_user: In current_user we get that user info which is login

# @login_required
"""
Decorator From flask_login means to access this route we need to required login first,
Jis routes ka sath @login_required  decorator use hoga wo protected route ban jai ga
"""

# Post.query.get_or_404(post_id)
"""
This means give me the post with this id if it doesn't exist then return a 404
"""

# db.session.add(post):
"""
session represents a set of operations (like inserts, updates, deletes) that you want to perform)
"""

# db.session.commit():
"""
Before committing changes are temporary, After committing changes are permanent in Database
"""

# form.validate_on_submit():
"""
Checks if a form has been submitted and if the input data is valid.
"""

# `f` string ka istemal hota hai username ke data ko message ke saath include karne ke liye.

flaskBlog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flaskBlog import db, bcrypt
from flaskBlog.models import User, Post
from flask_login import login_user, current_user, logout_user, login_required

from flaskBlog.users.forms import LoginForm, RegistrationForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from flaskBlog.users.utils import send_reset_email
from flaskBlog.common.common import save_picture

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')  # -->Hash Password
        user = User(username=form.username.data, email=form.email.data,
                    password=hashed_password)  # -->Add Data In User Model/Table
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in',
              'success')  # 2nd argument is category its bootstrap class of alert
        return redirect(url_for('users.login'))  # --> login is route function
    return render_template("register.html", title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user,
                       remember=form.remember.data)  # -->remember is Remember Me that we define in LoginForm class in user forms file
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template("login.html", title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data, "user_profile_pics")
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your Account Has Been Updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='user_profile_pics/' + current_user.image_file)
    return render_template("account.html", title='Account', image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template("user_posts.html", posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password', 'info')
        return redirect(url_for('users.login'))
    return render_template("reset_request.html", title="Reset Password", form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in',
              'success')
        return redirect(url_for('users.login'))
    return render_template("reset_token.html", title="Reset Password", form=form)


""" Descriptions """

# render_template is for html files, url_for is for css files, flash is for alert messages, paginate is for pagination

# request:
"""
Gives you access to details of the incoming HTTP request, such as form data, 
query parameters, and headers.
"""

# Blueprint:
"""
Flask mein Blueprint ek module hai jo apki application ko chote-chote parts mein divide 
karne ki facility deta hai.
"""

# db, bcrypt are instance that we define in __init__.py

# current_user: In current_user we get that user info which is login

# @login_required
"""
Decorator From flask_login means to access this route we need to required login first,
Jis routes ka sath @login_required  decorator use hoga wo protected route ban jai ga
"""

# login_user and logout_user:
"""
login_user(user): Logs in the user by setting the user’s session data. 
It keeps the user logged in across requests.

logout_user(): Logs out the current user by removing their session data, 
effectively ending their login session.
"""

# form.validate_on_submit():
"""
Checks if a form has been submitted and if the input data is valid.
"""

# bcrypt
"""
bcrypt: For Hashed Password
"""

# db.session.add(user):
"""
session represents a set of operations (like inserts, updates, deletes) that you want to perform)
"""

# db.session.commit():
"""
Before committing changes are temporary, After committing changes are permanent in Database
"""

# request.args.get:
"""
'request.args' URL parameters ko represent karta hai.
.get('page') yai function URL mein 'page' parameter ko get karta hai.
"""

# page = request.args.get('page', 1, type=int)
"""
request.args.get('page', 1, type=int) ka matlab hai ke URL mein agar page parameter diya gaya hai, to uski value le lo. Agar page parameter nahi diya gaya, to default value 1 set kar lo,
type=int means page value should be integer
"""

# User.query.filter_by(username=username).first_or_404():
"""
This statement tries to find a user with the given username. If found, it returns the user object; 
if not, it triggers a 404 error indicating that the user was not found.
"""

# Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
"""
Post.date_posted.desc(): new post will be shown on top
per_page=1 means eik page pr eik post hogi
"""

# `f` string ka istemal hota hai username ke data ko message ke saath include karne ke liye.

flaskBlog/templates/about.html
{% extends "layout.html" %} <!-- import layout.html file -->
{% block content %} <!-- content Block Start Here -->
<h1>About Page</h1>
{% endblock content %} <!-- content Block End Here -->

flaskBlog/templates/home.html
{% extends "layout.html" %}

{% block content %}
    <div class="row">
        <!-- Using for loop: for Block Start Here. Where Posts is pagination object that why we use posts.items  -->
        {% for post in posts.items %}
            <div class="col-12 col-sm-6 col-md-4 mb-4">
                <div class="card shadow-sm h-100 d-flex flex-column">
                    <img class="card-img-top"
                         src="{{ url_for('static', filename='post_profile_pics/' + post.image_file) }}"
                         alt="Card image cap" style="object-fit: cover; height: 200px;">
                    <div class="card-body d-flex flex-column">
                        <div class="d-flex align-items-center mb-3">
                            <img class="rounded-circle article-img"
                                 src="{{ url_for('static', filename='user_profile_pics/' + post.author.image_file) }}">
                            <div class="ml-3 text-truncate" style="max-width: 75%;">
                                <a class="mr-2 text-truncate d-block"
                                   href="{{ url_for('users.user_posts', username=post.author.username) }}"
                                   style="text-decoration: none;">{{ post.author.username }}</a>
                                <small class="text-muted d-block">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                            </div>
                        </div>
                        <h5 class="card-title mt-3">
                            <a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}"
                               style="text-decoration: none;">{{ post.title }}</a>
                        </h5>
                        <div class="flex-grow-1 mb-3">
                            <p class="card-text"
                               style="overflow: hidden; text-overflow: ellipsis; display: -webkit-box; -webkit-line-clamp: 3; -webkit-box-orient: vertical;">
                                {{ post.content }}
                            </p>
                        </div>
                        <div class="mt-auto d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{{ url_for('posts.post', post_id=post.id) }}"
                                   class="btn btn-sm btn-outline-secondary">View</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="row">
        <div class="col-12">
            {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                <!-- left_edge=1 and right_edge=1 means 1st or last pagination link hmesha dikha ga, left_current=1 and right_current=2 means current active page ka left pr 1 page or right pr 2 pages dikha ga -->
                {% if page_num %}
                    {% if posts.page == page_num %}
                        <a class="btn btn-info mb-4"
                           href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
                    {% else %}
                        <a class="btn btn-outline-info mb-4"
                           href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
                    {% endif %}
                {% else %}
                    ...
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock content %}

flaskBlog/templates/layout.html
<!-- 
 How write basic HTML structure:
 Type ! and then press tab or Enter
-->
<!-- layout file is for to avioding similar code in different html files -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- First import url_for in your main .py file then Here Link the main.css file -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <!-- static is folder name in which main.css file -->

    {% if title %} <!-- Using if else: if Block Start Here -->
        <title>Flask Blog - {{ title }}</title>
    {% else %}
        <title>Flask Blog</title>
    {% endif %} <!-- if Block End Here -->
</head>

<body>
<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
            <a class="navbar-brand mr-4" href="/">Flask Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <!-- In url_for these home, about, new_post, account, logout, login, register are functions of her routes  -->
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                    <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav ms-auto">
                    {% if current_user.is_authenticated %} <!-- If User Login -->
                        <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                    {% else %}
                        <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>

<main role="main" class="container">
    <div class="row">
        <div class="col-md-8">
            {% with messages = get_flashed_messages(with_categories=true) %}
                <!-- get_flashed_messages is function that get the flashed messages that we send to this template, with_categories=true will allow us to grab that category that we passed into the flash with message  -->
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                            {{ message }}
                        </div>
                    {% endfor %} <!-- for block end here -->
                {% endif %} <!-- if block end here -->
            {% endwith %} <!-- with block end here -->
            {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
            <div class="content-section">
                <h3>Our Sidebar</h3>
                <p class='text-muted'>You can put any information here you'd like.
                <ul class="list-group">
                    <li class="list-group-item list-group-item-light">Latest Posts</li>
                    <li class="list-group-item list-group-item-light">Announcements</li>
                    <li class="list-group-item list-group-item-light">Calendars</li>
                    <li class="list-group-item list-group-item-light">etc</li>
                </ul>
                </p>
            </div>
        </div>
    </div>
</main>

<!-- Optional JavaScript; choose one of the two! -->
<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
<!-- Option 2: Separate Popper and Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>

<!-- Common Function For Images -->
<script>
    function previewImage(event, previewId) {
        let reader = new FileReader();
        reader.onload = function () {
            let output = document.getElementById(previewId);
            output.src = reader.result;
        };
        reader.readAsDataURL(event.target.files[0]);
    }
</script>

</body>

</html>

flaskBlog/templates/login.html
{% extends "layout.html" %}
<!-- import layout.html file -->
{% block content %}
    <!-- content Block Start Here -->
    <div class="content-section">
        <form method="POST" action="">
            <!-- action means that when we post this form its just going to go back to the same route its going to post that information to the same route that were currently on -->
            {{ form.hidden_tag() }}
            <!-- form.hidden_tag() Ye tag CSRF (Cross-Site Request Forgery) attacks se bachane ke liye istemal hota hai. Is tag ka use karte hue, form submissions ko authenticate kiya jata hai Flask-WTF ke through,
         jisse website secure rehta hai. -->
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group mb-3">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group mb-3">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check mb-3">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group mb-3">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}" style="text-decoration: none;">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">Need An Account? <a class="ml-2" style="text-decoration: none;"
                                                      href="{{ url_for('users.register') }}">Sign Up Now</a>
            <!-- url_for('users.register') means link/redirect to the register page. The value that we're passing into the url_for function is not the name of the route its the name of the route function -->
        </small>
    </div>
{% endblock content %}
<!-- content Block End Here -->

flaskBlog/templates/post.html
{% extends "layout.html" %} <!-- import layout.html file -->
{% block content %} <!-- content Block Start Here -->
    <article class="media content-section">
        <img class="rounded-circle article-img"
             src="{{ url_for('static', filename='post_profile_pics/' + post.image_file) }}">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}"
                   style="text-decoration: none;">{{ post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                {% if post.author == current_user %}
                    <div>
                        <!--  update_post is function in update route  -->
                        <a class="btn btn-secondary btn-sm mt-1 mb-1"
                           href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
                        <button type="button" class="btn btn-danger btn-sm m-1" data-bs-toggle="modal"
                                data-bs-target="#deleteModal">Delete
                        </button>
                    </div>
                {% endif %}
            </div>
            <h2 class="article-title">{{ post.title }}</h2>
            <p class="article-content">{{ post.content }}</p>
        </div>
    </article>
    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="deleteModalLabel">Are You Sure About Deleting This Post?</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <!--  delete_post is function in delete route  -->
                    <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                        <input class="btn btn-danger" type="submit" value="Delete">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %} <!-- content Block End Here -->

flaskBlog/templates/user_posts.html
{% extends "layout.html" %} <!-- import layout.html file -->
{% block content %} <!-- content Block Start Here -->
    <h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>
    <!-- Using for loop: for Block Start Here. Where Posts is pagination object that why we use posts.items  -->
    {% for post in posts.items %}
        <article class="media content-section">
            <img class="rounded-circle article-img"
                 src="{{ url_for('static', filename='post_profile_pics/' + post.image_file) }}">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}"
                       style="text-decoration: none;">{{ post.author.username }}</a>
                    <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                </div>
                <!--  post is function in post/id route  -->
                <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}"
                       style="text-decoration: none;">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %} <!-- for Block End Here -->
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        <!-- left_edge=1 and right_edge=1 means 1st or last pagination link hmesha dikha ga, left_current=1 and right_current=2 means current active page ka left pr 1 page or right pr 2 pages dikha ga -->
        {% if page_num %}
            {% if posts.page == page_num %}
                <a class="btn btn-info mb-4"
                   href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4"
                   href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock content %} <!-- content Block End Here -->